### PR TITLE
handle relative path

### PR DESCRIPTION
**Pull request by shijunjuan**
I tried to use your plugin in sonar, and found it always says " [scapegoat] report source file not found: ...".
So I made this change and now it works fine. Could you please help merge this into your code base?

Thanks,
Jojo

### CODE REVIEW

**Comment by arthepsy** [comment]
Thanks! I'm looking to incorporate this (relative path support), but doing a bit local testing beforehand. I'm not sure it's the right way, as "sonar.sources" could contain multiple directories. Other plugins I looked at, handle this with fs.baseDir(). Wouldn't it work for Your project? What is Your "sonar.sources" property value?

**Comment by shijunjuan** [comment]
Here's the whole property file：

sonar.language=scala

sonar.scoverage.reportPath=target/scala-2.11/scoverage-report/scoverage.xml
sonar.scala.scapegoat.reportPath=target/scala-2.11/scapegoat-report/scapegoat.xml

sonar.sources=src/main/scala

sonar.modules=module1,module2

**Comment by arthepsy** [comment]
Great! Could You also give me a some line from scapegoat.xml, so I could see how exactly file path is generated there? 

By the way, all my scapegoat reports give out absolute path, - is there something special how to force it output relative paths?

**Comment by arthepsy** [comment]
Never mind the last question - created pretty empty project and got relative paths in scapegoat report.

**Comment by arthepsy** [comment]
I merged Your pull request and reworked it a bit. Released 1.1 version. Please check if everything is ok for You. Thanks again.

**Pull request merged**
